{% set version = "9.9" %}

package:
  name: coreutils-split
  version: "{{ version }}"

source:
  url: http://ftp.gnu.org/gnu/coreutils/coreutils-{{ version }}.tar.xz
  sha256: 19bcb6ca867183c57d77155eae946c5eced88183143b45ca51ad7d26c628ca75

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: coreutils
    script: build_coreutils.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make

    test:
      commands:
        - ln --relative --help
        - wc --version
        - cat --version

  - name: gnu-coreutils
    script: build_gnu-coreutils.sh


    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make

    test:
      commands:
        - gln --relative --help
        # to confirm gln vs ln
        - ln --version  # [linux64]
        - gln --version  # [linux64]
        - gwc --version
        - gcat --version

about:
  home: https://www.gnu.org/software/coreutils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.

  doc_url: https://www.gnu.org/software/coreutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/coreutils.git

extra:
  recipe-maintainers:
    - ngam
    - sodre
    - mbargull
    - h-vetinari
  feedstock-name: coreutils
