{% set name = "coreutils" %}
{% set version = "9.0" %}
{% set sha256 = "ce30acdf4a41bc5bb30dd955e9eaa75fa216b4e3deb08889ed32433c7b3b97ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: {{ name }}
    build:
      script_env:
        - GNU_PREFIX=0

    requirements:
      build:
        - {{ compiler('c') }}
        - make

    test:
      commands:
        - ln --relative --help
        - wc --version
        - cat --version

  - name: gnu-{{ name }}
    build:
      script_env:
        - GNU_PREFIX=1

    requirements:
      build:
        - {{ compiler('c') }}
        - make

    test:
      commands:
        - ln --relative --help
        - wc --version
        - cat --version

about:
  home: https://www.gnu.org/software/coreutils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.

  doc_url: https://www.gnu.org/software/coreutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/coreutils.git

extra:
  recipe-maintainers:
    - ngam
    - sodre
    - mbargull
