{% set name = "coreutils" %}
{% set version = "8.30" %}
{% set sha256 = "e831b3a86091496cdba720411f9748de81507798f6130adeaef872d206e1b057" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name  }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - ln --relative --help 
    - wc --version
    - cat --version

about:
  home: https://www.gnu.org/software/coreutils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.'

  doc_url: https://www.gnu.org/software/coreutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/coreutils.git

extra:
  recipe-maintainers:
    - sodre
    - mbargull
